// <auto-generated />
namespace AdvertisedOn.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ImagetoString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImagetoString));
        
        string IMigrationMetadata.Id
        {
            get { return "201212141754382_Image to String"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
